apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 127519609354.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 127519609354.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 7bce1345
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
